[theme]
base = "dark"
primaryColor = "#B04949"
backgroundColor = "#141414"
secondaryBackgroundColor = "#1f1f1f"
textColor = "#fafafa"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"