[theme]
base = "dark"
primaryColor = "#00BFB3"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#fafafa"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"